package OOP;
public class Main {
    public static void main(String[] args){
        System.out.println("this is first program");
        System.out.println("this is java!");

        //5*4*3*2*1
        long result =  1;
        for(int i=20 ; i>0; i--)
            result = result * i;
        System.out.println(result);

        // suitable for your problem
        // overloading
        // same method name with different parameters
        // byte code file generated by compiler for execution by JVM, java virtual machine
        // once compiler, run anywhere.
        // beyong the range of integer(16bit/32bit)
        // short/byte/char
        // long(64bit) is wider range than integer

    }
}
